Added to the production and mediamtx

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -56,11 +56,32 @@ jobs:
           docker push 809809510183.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/watchdog-backend:latest
 
       - name: Run database migrations
-        run: aws ecs run-task 
-          --cluster watchdog-prod-cluster 
-          --task-definition watchdog-backend-migrate 
-          --launch-type EC \
-          --overrides '{"containerOverrides":[{"name":"backend","command":["alembic","upgrade","head"]}]}'
+        run: |
+          TASK_ARN=$(aws ecs run-task \
+          --cluster watchdog-prod-cluster \
+          --task-definition watchdog-backend-task \
+          --launch-type EC2 \
+          --overrides '{"containerOverrides":[{"name":"backend","command":["alembic","upgrade","head"]}]}' \
+          --query 'tasks[0].taskArn' \
+          --output text)
+
+          echo "Migration task: $TASK_ARN"
+
+          aws ecs wait tasks-stopped \
+            --cluster watchdog-prod-cluster \
+            --tasks "$TASK_ARN"
+
+          EXIT_CODE=$(aws ecs desribe-tasks \
+            --cluster watchdog-prod-cluster \
+            --tasks "$TASK_ARN" \
+            --query 'tasks[0].container[0].exitCode' \
+            --output text)
+          
+          echo "Migration exit code: $EXIT_CODE"
+          if [ "$EXIT_CODE" != "0" ]; then 
+            echo "Migration failed"
+            exit 1
+          fi
 
       - name: Deploy new task definition to service
         run: | 
@@ -68,3 +89,7 @@ jobs:
             --cluster watchdog-prod-cluster
             --service watchdog-backend-service
             --force-new-deployment
+
+          aws ecs wait services-stable \
+            --cluster watchdog-prod-cluster \
+            --services wacthdog-backend-service
